plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2021: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'eslint:recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  object-curly-newline: ["error", {
        "ObjectExpression": { "multiline": true, "minProperties": 5 },
        "ObjectPattern": { "multiline": true },
        "ImportDeclaration": "never",
        "ExportDeclaration": "never"
    }]
